package com.omar.bankapp.entity;

import jakarta.persistence.*;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Entity representing a system user.
 *
 * A user can own multiple bank accounts.
 * This entity is mapped to the "users" table in the database.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Primary key of the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username used for login and identification.
     */
    private String name;

    /**
     * User password.
     * Hidden from JSON responses for security reasons.
     */
    @JsonIgnore
    private String password;

    /**
     * One user can have multiple bank accounts.
     * mappedBy indicates that the relationship is managed
     * on the BankAccount side.
     */
    @OneToMany(mappedBy = "user")
    private List<BankAccount> accounts;

    // Constructors

    public User() {}

    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set user password (usually hashed before saving).
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get encrypted password.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Retrieve all bank accounts owned by the user.
     */
    public List<BankAccount> getAccounts() {
        return accounts;
    }
}