package com.omar.bankapp.repository;

import com.omar.bankapp.entity.Transaction;
import org.springframework.data.jpa.repository.JpaRepository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Repository interface for Transaction entities.
 *
 * Provides database access operations for transaction records.
 * Inherits standard CRUD functionality from JpaRepository.
 */
public interface TransactionRepository extends JpaRepository<Transaction, Long> {

    /**
     * Retrieve transactions for a specific bank account
     * with pagination support.
     *
     * Pagination helps avoid loading large datasets into memory.
     *
     * Example query generated by Spring Data JPA:
     * SELECT t FROM Transaction t WHERE t.account.id = :accountId
     *
     * @param accountId the bank account ID
     * @param pageable pagination configuration (page number, size, sorting)
     * @return paginated list of transactions
     */
    Page<Transaction> findByAccountId(Long accountId, Pageable pageable);
}